<?php
// generated by Poedit from skkr-da_DK.po, do not edit directly
return ['domain'=>NULL,'plural-forms'=>'nplurals=2; plural=(n != 1);','language'=>'da_DK','pot-creation-date'=>'2026-02-06 13:04+0100','po-revision-date'=>'2026-02-06 13:04+0100','translation-revision-date'=>'2026-02-06 13:04+0100','project-id-version'=>'skkr','x-generator'=>'Poedit 3.8','messages'=>['Last updated:'=>'Sidst opdateret:','https://skkr.dk'=>'https://skkr.dk','https://robbert.dk'=>'https://robbert.dk']];
