import { readFileSync, writeFileSync } from "fs";
import { createHash } from "crypto";

function computeSri(filePath) {
  const content = readFileSync(filePath);
  const hash = createHash("sha384").update(content).digest("base64");
  return `sha384-${hash}`;
}

// 1. Compute CSS hash
const cssSri = computeSri("dist/styles/main.css");

// 2. Patch the placeholder in the built skkr.js
const skkrJsPath = "dist/scripts/skkr.js";
const skkrJs = readFileSync(skkrJsPath, "utf8");

if (!skkrJs.includes("__MAIN_CSS_INTEGRITY__")) {
  console.error("Placeholder __MAIN_CSS_INTEGRITY__ not found in dist/scripts/skkr.js");
  console.error("Did you forget to run a production build first?");
  process.exit(1);
}

writeFileSync(skkrJsPath, skkrJs.replace("__MAIN_CSS_INTEGRITY__", cssSri));

// 3. Compute skkr.js hash *after* patching
const jsSri = computeSri(skkrJsPath);

// 4. Write PHP constants file for use in header.php
const php = `<?php
// Auto-generated by scripts/generate-sri.mjs — do not edit manually.
// Re-run "npm run prod" to regenerate after any build.
define('SKKR_JS_SRI',  '${jsSri}');
define('SKKR_CSS_SRI', '${cssSri}');
`;

writeFileSync("dist/sri.php", php);

console.log("SRI hashes written to dist/sri.php");
console.log("  skkr.js  :", jsSri);
console.log("  main.css :", cssSri);
